### ISSUE TITLE
Some examples 

### ISSUE THREAD

**Issue by fyfef1** [git-disl/EnsembleBench#1]
This is really interesting work. Can the author provide some examples of the EnsembleBench use ？

**Comment by YanzhaoWu** [comment]
Thank you very much for your interest in this project.

We just released our recent work, DP-Ensemble (https://github.com/git-disl/DP-Ensemble), which is built on top of EnsembleBench. You could check it for the example of using EnsembleBench.

Best,
Yanzhao Wu
